In [95]:
# using Pkg
# Pkg.add("CairoMakie")
import CairoMakie
mak = CairoMakie

CairoMakie

# Forward Euler

$$ x'(t) = -2x(t) + t $$

$$ x_{n+1} = x_{n} + hx'_{n} $$

In [ ]:
t = 0   # initial value of the indepedent variable
h = 0.01 # step size
x0 = 1 # initial condition
N = 20 # number of iterations

dxdt(x,t) = -2 * x + t

X = zeros(N)
X[1] = x0


1

In [12]:
for i in collect(2:N)
    X[i] = X[i-1] + h * dxdt(X[i-1], t)
    t += h
end
X

20-element Vector{Float64}:
 1.0
 0.98
 0.9605
 0.94149
 0.9229602
 0.904900996
 0.88730297608
 0.8701569165584
 0.853453778227232
 0.8371847026626874
 0.8213410086094337
 0.805914188437245
 0.7908959046685001
 0.7762779865751301
 0.7620524268436275
 0.748211378306755
 0.7347471507406199
 0.7216522077258075
 0.7089191635712914
 0.6965407802998655

## Lorentz Atractor

In [90]:
a = 16
r = 50
b = 4

t = 0   # initial value of the indepedent variable
h = 0.01 # step size
N = 100 # number of iterations

# X = repeat([0.0; 0.0; 0.0], outer = [N])
X = []
x0 = [0; 1; 2]
push!(X,x0)


dxdt(x) = [a*(x[2] - x[1]); 
         r*x[1] - x[2] - x[1]*x[3];
         x[1]*x[2] - b*x[3]]




dxdt (generic function with 2 methods)

In [92]:
X[1] == [0; 1; 2]
dxdt(X[1])

3-element Vector{Int64}:
 16
 -1
 -8

In [94]:
for i in collect(2:N)
    X_next = X[i-1] .+ h .* dxdt(X[i-1])
    push!(X,X_next)
end
X

199-element Vector{Any}:
 [0, 1, 2]
 [0.16, 0.99, 1.92]
 [0.2928, 1.057028, 1.844784]
 [0.41507648, 1.187456192448, 1.774087617984]
 [0.5386572339916801, 1.3757560500866761, 1.708052964629795]
 [0.6725930445668795, 1.6221265557272617, 1.6471414555304733]
 [0.8245184063525407, 1.9311232535893532, 1.5921661076971483]
 [1.0015751819104306, 2.31094352161206, 1.5444019300644607]
 [1.2110741162626915, 2.7731533309106835, 1.5057716896423157]
 [1.4610067906063702, 3.332722844549653, 1.479125764251559]
 ⋮
 [-9.579766805293014, -17.849056629571084, 22.59817964891784]
 [-10.902853177177505, -20.29559655331437, 23.404150465018727]
 [-12.405692117359404, -22.99234701380328, 24.68078354005814]
 [-14.099556900790425, -25.903447584213417, 26.545911979543128]
 [-15.988179410138104, -28.95133559437707, 29.136346831763994]
 [-18.06228439961634, -31.997540538479836, 32.599684434953616]
 [-20.2919253818345, -34.82045961688442, 37.07518383049823]
 [-22.616490859442486, -37.094949073570156, 42.6579181603483]

In [98]:
fig = mak.Figure()
ax = mak.LScene(fig[1,1])


Makie.LScene()